#!/bin/sh

set -e

mvn clean package
mvn source:jar

mvn deploy:deploy-file \
  -DgroupId=blackboard.org.jenkins-ci.plugins \
  -DartifactId=artifact-manager-s3 \
  -Dpackaging=jpi \
  -Dversion=1.2-$(git rev-parse --short HEAD) \
  -Dfile=target/artifact-manager-s3.hpi \
  -Dsources=target/artifact-manager-s3-sources.jar \
  -DrepositoryId=maven-bbpd-io \
  -Durl=http://maven.bbpd.io/content/repositories/thirdparty/
